# Kinsta configuration file for SvelteKit project

[build]
  command = "npm run build"
  publish = "build"

[site]
  framework = "svelte"

[build.environment]
  NODE_VERSION = "18"

[http]
  headers = []

[[http.headers]]
  for = "/*"
  [http.headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"

[[http.redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# Enable HTTP/2
[http2]
  enable = true

# Enable compression
[compression]
  enable = true 