<script>
  // This file is auto-generated by download-fonts.js
</script>

<svelte:head>
  <!-- Preload critical fonts -->
  <link rel="preload" href="/fonts/inter-400.woff2" as="font" type="font/woff2" crossorigin="anonymous" fetchpriority="high">
<link rel="preload" href="/fonts/inter-700.woff2" as="font" type="font/woff2" crossorigin="anonymous" fetchpriority="high">
<link rel="preload" href="/fonts/fira-code-400.woff2" as="font" type="font/woff2" crossorigin="anonymous" fetchpriority="high">

  
  <!-- Font loading script -->
  <script>
    (function() {
      // Add loading class immediately
      document.documentElement.classList.add('fonts-loading');
      
      // Check if fonts are already cached
      if (localStorage.getItem('fonts-loaded')) {
        document.documentElement.classList.remove('fonts-loading');
        document.documentElement.classList.add('fonts-loaded');
      } else {
        // Use Font Loading API if available
        if ("fonts" in document) {
          Promise.all([
            document.fonts.load("1em Inter"),
            document.fonts.load("1em 'Fira Code'")
          ]).then(() => {
            document.documentElement.classList.remove('fonts-loading');
            document.documentElement.classList.add('fonts-loaded');
            localStorage.setItem('fonts-loaded', 'true');
          }).catch(() => {
            // If something goes wrong, still show content
            document.documentElement.classList.remove('fonts-loading');
          });
        } else {
          // Fallback for browsers without Font Loading API
          document.documentElement.classList.remove('fonts-loading');
        }
        
        // Failsafe - if fonts take too long, show content anyway
        setTimeout(function() {
          if (document.documentElement.classList.contains('fonts-loading')) {
            document.documentElement.classList.remove('fonts-loading');
          }
        }, 2000);
      }
    })();
  </script>
</svelte:head>
