<script>
    import { onMount } from 'svelte';
    import { fade, fly, scale } from 'svelte/transition';
    import AnimateInView from '$lib/components/ui/AnimateInView.svelte';
    import PageContainer from '$lib/components/layout/PageContainer.svelte';
    import SEO from '$lib/components/seo/SEO.svelte';
    import { generatePublicationSchema, jsonLdToString } from '$lib/utils/structured-data';
    
    export let data;
    const { publications } = data;
    
    let visible = false;
    
    // Generate structured data for the page
    const getPublicationsListSchema = () => {
        return {
            '@context': 'https://schema.org',
            '@type': 'CollectionPage',
            'name': 'Dr. Fatih Nayebi\'s Research Publications',
            'description': 'Research publications by Dr. Fatih Nayebi on AI, machine learning, retail technology, and agentic systems',
            'mainEntity': {
                '@type': 'ItemList',
                'itemListElement': publications.map((publication, index) => ({
                    '@type': 'ListItem',
                    'position': index + 1,
                    'item': {
                        '@type': 'ScholarlyArticle',
                        'headline': publication.title,
                        'author': Array.isArray(publication.authors) 
                            ? publication.authors.map(name => ({ '@type': 'Person', 'name': name }))
                            : [{ '@type': 'Person', 'name': publication.authors || 'Fatih Nayebi' }],
                        'datePublished': publication.date,
                        'publisher': publication.journal,
                        'url': publication.url || `/publications/${publication.slug}`
                    }
                }))
            }
        };
    };
    
    // SEO MetaData for the Publications Listing Page
    const pageTitle = "Research Publications on Retail AI & Agentic Systems | Dr. Fatih Nayebi";
    const pageDescription = "Explore Dr. Fatih Nayebi's research publications on AI for Retail, Agentic AI systems, machine learning, and advanced data science applications.";
    const keywords = "Retail AI research, Agentic AI publications, AI for inventory optimization, machine learning in retail, assortment planning, Fatih Nayebi publications";
    const siteUrl = "https://fatihnayebi.com"; // Define or import
    const canonicalUrl = `${siteUrl}/publications`;

    const openGraphData = {
      title: pageTitle,
      description: pageDescription,
      type: "website", // Or potentially "profile" or "object" if more suitable
      url: canonicalUrl,
      image: `${siteUrl}/images/social-card.jpg` // Default social card
    };

    const twitterData = {
      card: "summary_large_image",
      title: pageTitle,
      description: pageDescription,
      image: `${siteUrl}/images/social-card.jpg`
    };

    // Structured data is generated by getPublicationsListSchema
    const structuredData = (publications && publications.length > 0) ? getPublicationsListSchema() : null;

    onMount(() => {
        visible = true;
    });
</script>

<SEO 
  title={pageTitle}
  description={pageDescription}
  keywords={keywords}
  canonical={canonicalUrl}
  type="website"
  openGraph={openGraphData}
  twitter={twitterData}
  structuredData={structuredData}
/>

{#if visible}
<PageContainer heroSection={true}>
    <!-- Background decorative elements -->
    <div class="absolute top-20 right-10 opacity-10 w-64 h-64 bg-primary rounded-full blur-3xl"></div>
    <div class="absolute bottom-40 left-10 opacity-10 w-96 h-96 bg-indigo-400 rounded-full blur-3xl"></div>
    
    <h1 class="text-5xl font-bold mb-4 text-center text-primary" in:fly={{ y: -30, duration: 800, delay: 300 }}>Retail AI & Agentic Systems Research</h1>
    <p class="text-lg text-center mb-12 max-w-3xl mx-auto" in:fly={{ y: 30, duration: 800, delay: 500 }}>
        Publications exploring the intersection of artificial intelligence, retail operations, and autonomous agentic systems. My research focuses on practical applications of AI to solve real-world retail challenges through innovative approaches.
    </p>
    
    <div class="space-y-12">
        {#if publications && publications.length > 0}
            {#each publications as publication, i}
                <AnimateInView type="fly" x={-20} delay={300 + (i * 200)}>
                    <div class="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 transform transition-all duration-300 hover:shadow-md hover:-translate-y-1" style="transition-delay: {i * 150}ms">
                        <h2 class="text-2xl font-semibold mb-4 text-primary dark:text-blue-400">{publication.title}</h2>
                        
                        <div class="publication-meta mb-6 pb-4 border-b border-gray-100 dark:border-gray-700">
                            <div class="publication-authors text-gray-800 dark:text-gray-200 font-medium mb-2">
                                {#if publication.authors}
                                    {publication.authors.join(', ')}
                                {:else}
                                    Dr. Fatih Nayebi
                                {/if}
                            </div>
                            
                            <div class="flex flex-wrap justify-between items-center">
                                <div class="publication-journal text-gray-600 dark:text-gray-300 italic">
                                    {publication.journal || ''}
                                </div>
                                
                                <div class="publication-year font-medium bg-primary/10 text-primary dark:bg-blue-900/30 dark:text-blue-400 px-3 py-1 rounded-full text-sm">
                                    {publication.year || new Date(publication.date).getFullYear()}
                                </div>
                            </div>
                        </div>
                        
                        <div class="publication-content">
                            {#if publication.abstract}
                                <p class="text-gray-600 dark:text-gray-300 mb-4">{publication.abstract}</p>
                            {/if}
                            
                            <div class="publication-tags mb-6">
                                <div class="flex flex-wrap gap-2">
                                    {#if publication.tags && publication.tags.length > 0}
                                        {#each publication.tags as tag}
                                            <span class="bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-3 py-1 rounded-full text-xs">{tag}</span>
                                        {/each}
                                    {/if}
                                </div>
                            </div>
                            
                            <div class="publication-actions flex flex-wrap gap-4">
                                {#if publication.pdf}
                                    <a href={publication.pdf} target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center font-medium transition-all duration-300 rounded-lg px-4 py-2 text-sm bg-primary text-white hover:bg-primary-hover transform hover:scale-105">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                        </svg>
                                        PDF
                                    </a>
                                {/if}
                                
                                {#if publication.doi}
                                    <a href={`https://doi.org/${publication.doi}`} target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center font-medium transition-all duration-300 rounded-lg px-4 py-2 text-sm bg-transparent text-primary dark:text-blue-400 border border-primary dark:border-blue-400 hover:bg-primary/10 hover:text-primary dark:hover:bg-blue-900/30 dark:hover:text-white transform hover:scale-105">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101" />
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 015.656 0l4 4a4 4 0 01-5.656 5.656l-1.102-1.101" />
                                        </svg>
                                        DOI
                                    </a>
                                {/if}
                                
                                {#if publication.url}
                                    <a href={publication.url} target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center font-medium transition-all duration-300 rounded-lg px-4 py-2 text-sm bg-transparent text-primary dark:text-blue-400 border border-primary dark:border-blue-400 hover:bg-primary/10 hover:text-primary dark:hover:bg-blue-900/30 dark:hover:text-white transform hover:scale-105">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                                        </svg>
                                        Publication Link
                                    </a>
                                {/if}
                                
                                <a href={`/publications/${publication.slug}`} class="inline-flex items-center justify-center font-medium transition-all duration-300 rounded-lg px-4 py-2 text-sm bg-transparent text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 transform hover:scale-105">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                    </svg>
                                    Details
                                </a>
                            </div>
                        </div>
                    </div>
                </AnimateInView>
            {/each}
        {:else}
            <div class="text-center py-10 text-gray-500 dark:text-gray-400">
                <p>No publications found.</p>
            </div>
        {/if}
    </div>
</PageContainer>
{/if}

<style>
    h1 {
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    
    .publication-meta {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }
    
    .publication-authors {
        font-weight: 500;
    }
    
    .publication-journal {
        font-style: italic;
        color: #666;
    }
    
    .publication-date {
        font-weight: 600;
    }
    
    .publication-content {
        line-height: 1.6;
    }
    
    @media (max-width: 768px) {
        h1 {
            font-size: 2rem;
        }
    }
</style> 